# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'



- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script:  chown $(id -u root):$(id -g root) ./spec/
  displayName: 'permissao'
   
   
- script: chmod +s wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  displayName: 'Baixando o chrome'


- script: chmod +s apt install ./google-chrome-stable_current_amd64.deb
  displayName: 'instalando o chrome'

- script: rspec --init
  displayName: 'rspec install'

- script: chmod +s rspec --tag @testes
  displayName: 'rspec install'


